const quotePowerShellString = (value = '') =>
  `'${String(value).replace(/'/g, "''")}'`;

const normalizeText = (value) => String(value || '').trim().replace(/\s+/g, ' ');

export const buildNotepadControlledTextInputScript = ({
  text = 'alice field interaction ok',
  inputText = text,
  expectedText = text,
  fileName = 'alice-learning-notepad.txt',
  marker = 'alice-learning-vm:field-interacted',
  allowSendKeysFallback = true,
  closeExistingTargetProcesses = false,
  forceMismatchFileOnActivationFailure = false,
} = {}) => {
  const safeFileName = normalizeText(fileName) || 'alice-learning-notepad.txt';
  return [
    `$text = ${quotePowerShellString(expectedText)}`,
    `$inputText = ${quotePowerShellString(inputText)}`,
    `$allowSendKeysFallback = ${allowSendKeysFallback ? '$true' : '$false'}`,
    `$closeExistingTargetProcesses = ${closeExistingTargetProcesses ? '$true' : '$false'}`,
    `$forceMismatchFileOnActivationFailure = ${forceMismatchFileOnActivationFailure ? '$true' : '$false'}`,
    "$targetProcessName = 'notepad'",
    `$file = Join-Path $env:TEMP ${quotePowerShellString(safeFileName)}`,
    '$diagnosticsEmitted = $false',
    "$diagnostics = [ordered]@{ driver = 'vmTextInputDriver'; target = 'notepad'; expectedText = $text; actualTextPreview = ''; inputMethod = ''; clipboardPasteAttempted = $false; sendKeysFallbackUsed = $false; activeWindowConfirmed = $false; activeWindowBeforeInput = ''; activeWindowAfterInput = ''; saveAttempted = $false; fileExists = $false; fileSize = -1; fileUpdated = $false; fileLastWriteTimeChanged = $false; validationPassed = $false; failureReason = ''; warnings = @() }",
    "trap { if ($diagnostics -and -not $diagnosticsEmitted) { $diagnostics.validationPassed = $false; if (-not $diagnostics.failureReason) { $diagnostics.failureReason = if ($_.Exception.Message) { $_.Exception.Message } else { [string]$_ } }; $diagnosticsJson = $diagnostics | ConvertTo-Json -Compress -Depth 4; Write-Output ('vm_text_input_diagnostics=' + $diagnosticsJson); $diagnosticsEmitted = $true }; break }",
    "Set-Content -LiteralPath $file -Value '' -Encoding UTF8",
    '$beforeWrite = (Get-Item -LiteralPath $file).LastWriteTimeUtc',
    'if ($closeExistingTargetProcesses) { Get-Process -Name $targetProcessName -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue; Start-Sleep -Milliseconds 300 }',
    '$beforeIds = @(Get-Process -Name $targetProcessName -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Id)',
    'Start-Process -FilePath notepad.exe -ArgumentList $file | Out-Null',
    '$windowProcess = $null',
    'for ($i = 0; $i -lt 32; $i++) { $processes = @(Get-Process -Name $targetProcessName -ErrorAction SilentlyContinue); $windowProcess = $processes | Where-Object { $_.MainWindowHandle -ne 0 -and ($beforeIds -notcontains $_.Id) } | Select-Object -First 1; if (-not $windowProcess) { $windowProcess = $processes | Where-Object { $_.MainWindowHandle -ne 0 } | Select-Object -First 1 }; if ($windowProcess) { break }; Start-Sleep -Milliseconds 250 }',
    "if (-not $windowProcess) { throw 'field_window_not_detected' }",
    '$shell = New-Object -ComObject WScript.Shell',
    '$activated = $false',
    'for ($i = 0; $i -lt 12; $i++) { $activated = $shell.AppActivate([int]$windowProcess.Id); if ($activated) { break }; Start-Sleep -Milliseconds 250 }',
    "if (-not $activated) { throw 'field_window_not_activated' }",
    'Add-Type -AssemblyName System.Windows.Forms | Out-Null',
    'Add-Type -TypeDefinition \'using System; using System.Runtime.InteropServices; public static class AliceVmWindow { [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow(); }\' | Out-Null',
    '$diagnostics.activeWindowBeforeInput = [string][AliceVmWindow]::GetForegroundWindow()',
    'for ($i = 0; $i -lt 16; $i++) { if ([AliceVmWindow]::GetForegroundWindow() -eq [IntPtr]$windowProcess.MainWindowHandle) { $diagnostics.activeWindowConfirmed = $true; break }; $shell.AppActivate([int]$windowProcess.Id) | Out-Null; Start-Sleep -Milliseconds 150 }',
    "if (-not $diagnostics.activeWindowConfirmed) { if ($forceMismatchFileOnActivationFailure) { [System.IO.File]::WriteAllText($file, $inputText, [System.Text.UTF8Encoding]::new($false)); $item = Get-Item -LiteralPath $file; $content = Get-Content -LiteralPath $file -Raw -Encoding UTF8; $diagnostics.inputMethod = 'controlled_negative_file_write'; $diagnostics.fileExists = $true; $diagnostics.fileSize = $item.Length; $diagnostics.fileUpdated = $item.LastWriteTimeUtc -gt $beforeWrite; $diagnostics.fileLastWriteTimeChanged = $diagnostics.fileUpdated; $diagnostics.expectedLength = $text.Length; $diagnostics.actualLength = $content.Length; $diagnostics.actualTextPreview = if ($content.Length -le 240) { $content } else { $content.Substring(0, 240) }; $diagnostics.validationPassed = $false; $diagnostics.failureReason = 'controlled_text_file_mismatch'; $diagnosticsJson = $diagnostics | ConvertTo-Json -Compress -Depth 4; $diagnosticsEmitted = $true; Write-Output ('vm_text_input_diagnostics=' + $diagnosticsJson); throw 'controlled_text_file_mismatch' }; throw 'field_window_not_active' }",
    "try { Set-Clipboard -Value $inputText -ErrorAction Stop; $diagnostics.clipboardPasteAttempted = $true; $diagnostics.inputMethod = 'clipboard_paste'; [System.Windows.Forms.SendKeys]::SendWait('^a'); Start-Sleep -Milliseconds 100; [System.Windows.Forms.SendKeys]::SendWait('^v'); Start-Sleep -Milliseconds 150 } catch { $diagnostics.warnings += ('clipboard_paste_failed:' + $_.Exception.Message) }",
    "if ($allowSendKeysFallback -and -not $diagnostics.clipboardPasteAttempted) { $diagnostics.inputMethod = 'sendkeys_fallback'; $diagnostics.sendKeysFallbackUsed = $true; [System.Windows.Forms.SendKeys]::SendWait('^a'); Start-Sleep -Milliseconds 100; [System.Windows.Forms.SendKeys]::SendWait($inputText); Start-Sleep -Milliseconds 150 }",
    "[System.Windows.Forms.SendKeys]::SendWait('^s')",
    '$diagnostics.saveAttempted = $true',
    '$content = $null',
    'for ($i = 0; $i -lt 20; $i++) { Start-Sleep -Milliseconds 250; if (Test-Path -LiteralPath $file -PathType Leaf) { $diagnostics.fileExists = $true; $item = Get-Item -LiteralPath $file; $diagnostics.fileSize = $item.Length; $content = Get-Content -LiteralPath $file -Raw -Encoding UTF8; if ($item.LastWriteTimeUtc -gt $beforeWrite) { $diagnostics.fileUpdated = $true; $diagnostics.fileLastWriteTimeChanged = $true }; if ($content -ceq $text) { $diagnostics.validationPassed = $true; break } } }',
    "if ($allowSendKeysFallback -and -not $diagnostics.validationPassed -and -not $diagnostics.sendKeysFallbackUsed) { $diagnostics.warnings += 'clipboard_paste_content_mismatch'; $diagnostics.inputMethod = 'sendkeys_fallback'; $diagnostics.sendKeysFallbackUsed = $true; $shell.AppActivate([int]$windowProcess.Id) | Out-Null; Start-Sleep -Milliseconds 150; [System.Windows.Forms.SendKeys]::SendWait('^a'); Start-Sleep -Milliseconds 100; [System.Windows.Forms.SendKeys]::SendWait($inputText); Start-Sleep -Milliseconds 150; [System.Windows.Forms.SendKeys]::SendWait('^s'); $diagnostics.saveAttempted = $true; for ($i = 0; $i -lt 20; $i++) { Start-Sleep -Milliseconds 250; if (Test-Path -LiteralPath $file -PathType Leaf) { $diagnostics.fileExists = $true; $item = Get-Item -LiteralPath $file; $diagnostics.fileSize = $item.Length; $content = Get-Content -LiteralPath $file -Raw -Encoding UTF8; if ($item.LastWriteTimeUtc -gt $beforeWrite) { $diagnostics.fileUpdated = $true; $diagnostics.fileLastWriteTimeChanged = $true }; if ($content -ceq $text) { $diagnostics.validationPassed = $true; break } } } }",
    '$diagnostics.activeWindowAfterInput = [string][AliceVmWindow]::GetForegroundWindow()',
    '$diagnostics.filePath = $file',
    '$diagnostics.windowHandle = [string]$windowProcess.MainWindowHandle',
    '$diagnostics.expectedLength = $text.Length',
    '$diagnostics.actualLength = if ($null -eq $content) { -1 } else { $content.Length }',
    '$diagnostics.actualTextPreview = if ($null -eq $content) { "" } elseif ($content.Length -le 240) { $content } else { $content.Substring(0, 240) }',
    '$diagnostics.contentHash = if ($null -eq $content) { "" } else { [Convert]::ToBase64String([System.Security.Cryptography.SHA256]::Create().ComputeHash([System.Text.Encoding]::UTF8.GetBytes($content))) }',
    "if (-not $diagnostics.validationPassed) { if (-not $diagnostics.fileExists) { $diagnostics.failureReason = 'controlled_text_file_missing' } elseif (-not $diagnostics.fileLastWriteTimeChanged) { $diagnostics.failureReason = 'controlled_text_file_not_updated' } else { $diagnostics.failureReason = 'controlled_text_file_mismatch' } }",
    '$diagnosticsJson = $diagnostics | ConvertTo-Json -Compress -Depth 4',
    '$diagnosticsEmitted = $true',
    "Write-Output ('vm_text_input_diagnostics=' + $diagnosticsJson)",
    "if (-not $diagnostics.validationPassed) { throw 'controlled_text_file_mismatch' }",
    `Write-Output ${quotePowerShellString(marker)}`,
    "Write-Output 'target_profile=notepad'",
    "Write-Output ('file_path=' + $file)",
    "Write-Output ('window_handle=' + $windowProcess.MainWindowHandle)",
    "Write-Output ('typed_text=' + $inputText)",
    "Write-Output ('input_method=' + $diagnostics.inputMethod)",
  ].join('; ');
};
